kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: proj2
  namespace: default
  #labels:
spec:
  selector:                #kube automatically assign the names
    matchLabels:
      app: proj2           #name should match- proj2
  template:
    metadata:
     #name:                #it is already assigned
     labels:
       app: proj2
    spec:
     containers:
      - name: cont1
        image: nikhiltr1/proj2:23
---
kind: Service
apiVersion: v1
metadata:
  name: proj2-svc
  namespace: default
  #labels: optional
spec:
  type: NodePort
  selector:
    app: proj2                        #Label name of the pods where you want to send traffic(instead of IP's)
  ports:
    - name: cont1port
      port: 80                        #Port of the image which is defined earlier
      nodePort: 30008                 #Ranges from 30000-32767

